print('  ' * 0, end='')
print(0, end=' ')
print(1, end=' ')
print(2, end=' ')
print(3, end=' ')
print(4, end=' ')
print()

print('  ' * 1, end='')
print(0, end=' ')
print(1, end=' ')
print(2, end=' ')
print(3, end=' ')
print()

print('  ' * 2, end='')
print(0, end=' ')
print(1, end=' ')
print(2, end=' ')
print()

print('  ' * 3, end='')
print(0, end=' ')
print(1, end=' ')
print()

print('  ' * 4, end='')
print(0, end=' ')
print()

